// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'errorActive': string;
  'noError': string;
  'numberInputContainer': string;
  'separator': string;
}
export const cssExports: CssExports;
export default cssExports;
